version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
  app:
    # image: quay.io/apicurio/apicurio-registry-sql:latest-snapshot
    image: quay.io/famargon/apicurio-registry-sql:latest-local
    ports:
      - 8080:8080
    environment:
      REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
      REGISTRY_DATASOURCE_USERNAME: apicurio-registry
      REGISTRY_DATASOURCE_PASSWORD: password
      REGISTRY_ENABLE_MULTITENANCY: "true"
      REGISTRY_LOG_LEVEL: DEBUG
      LOG_LEVEL: DEBUG
    depends_on:
      - postgres