name: release-build

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '21.0.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Get maven wrapper
      run: mvn -N io.takari:maven:wrapper -Dmaven=3.6.3
    - name: Set version
      run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
    - name: Build jvm jar
      run: ./mvnw -pl cli -am install
    - name: Upload jvm
      id: upload-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./cli/target/apicurio-registry-cli-${{ github.event.release.tag_name }}-runner.jar
        asset_name: apicurio-registry-cli-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/octet-stream
    - name: Build native executable
      run: ./mvnw -pl cli package -Dnative
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./cli/target/apicurio-registry-cli-${{ github.event.release.tag_name }}-runner
        asset_name: apicurio-registry-cli-${{ github.event.release.tag_name }}-linux
        asset_content_type: application/octet-stream