name: cli win test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cli-win:
    name: cli win test

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        # GraalVM version, no pattern syntax available atm
        graalvm: '21.0.0.2'
        # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
        java: 'java11'
        # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
        arch: 'amd64'
    - name: Install native-image
      run: |
        gu.cmd install native-image
      shell: cmd
    - name: Configure Pagefile
      # Increased the page-file size due to memory-consumption of native-image command
      # For details see https://github.com/actions/virtual-environments/issues/785
      uses: al-cheb/configure-pagefile-action@v1.2
    - name: Set version
      run: mvn versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      shell: cmd
    - name: Build jvm jar
      run: mvn -pl cli -am install
    - name: Build native executable
      # Invoke the native-image build with the necessary Visual Studio tooling/environment intialized
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        mvn -pl cli package -Dnative
      shell: cmd
    